name: API-Podium-Pipeline

on:
 workflow_dispatch:
 
jobs:
  install-prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt-get install wget
          sudo apt-get install fontconfig

  # This workflow contains a single job called "build"
  validate-api-on-swaggerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      # - name: Check the API definition exists 
        # env:
         #  SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        # run: |
        #   swaggerhub api:get AlexsDemoOrg/ADefinitelyRealAPI/1.0.0
      # - name: Validate definition
      #   env:
       #    SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
       #  run: |
       #    swaggerhub api:validate AlexsDemoOrg/ADefinitelyRealAPI/1.0.0

  download-and-install-readyapi:
    runs-on: ubuntu-latest
    needs: install-prerequisites
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ReadyAPI
        run: |
          wget "https://dl.eviware.com/ready-api/3.53.0/ReadyAPI-x64-3.53.0.sh"

      - name: Make file executable
        run: chmod +x ${{ github.workspace }}/ReadyAPI-x64-3.53.0.sh

      - name: Install ReadyAPI
        run: sudo sh ${{ github.workspace }}/ReadyAPI-x64-3.53.0.sh -q

      - name: Run Tests
        run: sudo sh /opt/SmartBear/ReadyAPI-3.53.0/bin/testrunner.sh -r -a -j -f${{ github.workspace }} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" -accessKey ${{ secrets.SLM_ACCESSKEY }} ${{ github.workspace }}/PetStoreForAzurePipeline-readyapi-project.xml
