name: API-Podium-Pipeline

on:
 workflow_dispatch:
 
env:
  swaggerhub_owner: MConneely
  swaggerhub_project_name: ProjectManagement
  swaggerhub_api_name: ProjectManagementAPI 
  swaggerhub_api_version: 1.0.0 
  swaggerhub_api_key: ${{secrets.SWAGGERHUB_API_KEY}}
  slm_access_key:  ${{secrets.SLM_ACCESSKEY}} 
  pact_broker_base_url: https://mconneely-sb.pactflow.io
jobs:
  install-prerequisites:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt-get install wget
          sudo apt-get install fontconfig
          
      - uses: actions/checkout@v2
      - name: Use Nodejs 16.x
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

  validate-api-on-swaggerhub:
    runs-on: ubuntu-latest
    needs: install-prerequisites
    steps:
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Check the API definition exists
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:get $swaggerhub_owner/$swaggerhub_api_name/$swaggerhub_api_version
      - name: Validate definition
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}      
        run: |
          swaggerhub api:validate $swaggerhub_owner/$swaggerhub_api_name/$swaggerhub_api_version

  build-and-run-api-service:
    runs-on: ubuntu-latest
    steps:
      - name: Build and run api
        run: |
          echo API built and running
          
  run-functional-tests-readyapi:
    runs-on: ubuntu-latest
    needs: validate-api-on-swaggerhub
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download ReadyAPI
        run: |
          wget "https://dl.eviware.com/ready-api/3.53.0/ReadyAPI-x64-3.53.0.sh"

      - name: Make file executable
        run: chmod +x ${{ github.workspace }}/ReadyAPI-x64-3.53.0.sh

      - name: Install ReadyAPI
        run: sudo sh ${{ github.workspace }}/ReadyAPI-x64-3.53.0.sh -q

      #- name: Run Tests
      #  run: sudo sh /opt/SmartBear/ReadyAPI-3.53.0/bin/testrunner.sh -r -a -j -f${{ github.workspace }} "-RJUnit-Style HTML Report" -FXML "-EDefault environment" -accessKey $slm_access_key ${{ github.workspace }}/PetStoreForAzurePipeline-readyapi-project.xml


  set-api-to-published-on-swaggerhub:
    runs-on: ubuntu-latest
    needs: run-functional-tests-readyapi
    steps:
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Publish SwaggerHub API
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:publish $swaggerhub_owner/$swaggerhub_api_name/$swaggerhub_api_version

  published-openapi-to-pactflow:
    runs-on: ubuntu-latest
    needs: set-api-to-published-on-swaggerhub
    steps:
      - name: Install SwaggerHub CLI
        env:
         SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
        run: |
            docker run --rm \
               -w ${PWD} \
               -v ${PWD}:${PWD} \
               -e $pact_broker_base_url \
               -e ${{secrets.PACTFLOW_API_KEY}} \ 
              pactfoundation/pact-cli:latest \
              pactflow publish-provider-contract \
              MConneely-AutoMockAPI.yaml \
              --provider "pactflow-example-bi-directional-provider-rapi" \
              --provider-app-version 3a0994c \
              --branch test-pactflow-command \
              --content-type application/yaml \
              --verification-exit-code=0 \
              --verification-results TEST-Test_Suite_1.xml \
              --verification-results-content-type text/plain \
              --verifier readyapi
      
  published-api-to-swaggerhub-portal:
    runs-on: ubuntu-latest
    needs: set-api-to-published-on-swaggerhub
    steps:
    - name: Link an API
      env:
        SWAGGERHUB_API_KEY: ${{ secrets.SWAGGERHUB_API_KEY }}
      run: |
            curl -X POST "https://api.portal.swaggerhub.com/v1/sections/f3ec3f73-35ed-40d8-9b9d-30598cb14a6a/table-of-contents" \
            -H "Authorization: Bearer $SWAGGERHUB_API_KEY" \
            -H "Content-Type: application/json" \
            --data '{
                "slug": "payee-api-podium-1.0.0",
                "title": "Payee API",
                "order": 1,
                "content": {
                  "type": "apiUrl",
                   "url": "https://api.swaggerhub.com/apis/MConneely/Banking_API/2.0.0/swagger.json"
                    } 
                }'
